name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - uses: actions/checkout@master

    - name: Create a Release

      uses: elgohr/Github-Release-Action@master

      env:

        GITHUB_TOKEN: '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'

      with:

        args: MyReleaseMessage
